[tool.poetry]
name = "certbot-docker"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10,>=3.10.4"
certbot-dns-ovh = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
